### ISSUE TITLE
Geoportal Harvest Console bugs

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#113]
Hi,
there are some problems within the Geoportal Harvesting console.

1. There are no icons shown in console (see screen 1)
2. The harvested metadata count is not shown (see screen 1)
3. Not able to calculate indicators report (see screen 2)

Can you have a look into this?

![image](https://user-images.githubusercontent.com/45065613/177714963-9da17ec3-1c5a-4ce4-b567-c36436769ad3.png)

![image](https://user-images.githubusercontent.com/45065613/177715060-e72f31b4-16fa-4963-9c91-9629be1e34ab.png)

**Comment by jescriu** [comment]
Dear @manilly,
I will check this with out INSPIRE Geoportal IT team and will let you know.
Regards.

**Comment by dartasensi** [comment]
Dear @manilly 

thanks for reporting us this bug.
There was an automatic update within the icon libraries, that generated this unexpected behavior.
Fixed, now it should be working as usual.

Regards

**Comment by manilly** [comment]
Hi @dartasensi ,
thanks, the icons are back. Unfortunately I still have the problem, that there are no numbers shown for the harvesting report (see screen). So I can't review the result and publish it...

![image](https://user-images.githubusercontent.com/45065613/178917419-74af5b63-32da-465b-b78a-959964fd8223.png)

**Comment by manilly** [comment]
@dartasensi problem still appears on harvesting today. Can you have a look into it an reopen bug?
