### ISSUE TITLE
ES: The LinkChecker doesn´t recognize our SDI Digital certificate

### ISSUE THREAD

**Issue by MarisolGomezAndres** [INSPIRE-MIF/helpdesk-geoportal#9]
There is some problem  in recognising our SDI certificate from FNMyT as a valid Authorisation Entity and that´s the reason by our metadata and services are not validated. Therefore, if the FNMyT Certification Authorities shoud be  included as a valid Authorisation Entity. We have analysed the validation errors and discover that both the validator and the linnkChecker don´t recognise our certificate.   The same error has happened in the past and you solved it by recognising the Authorisation Entity that we use to securize our SDI,  FNMyT,  as a valid entity in your platform. 

Atacched you can find two  examples URL to  test it:

Watwerbody  PHC 2015-2021: https://wms.mapama.gob.es/sig/agua/PHC/MasasAguaSub2021/wms.aspx?request=getcapabilities
 ATOM download service MAPA/MITECO: https://www.mapama.gob.es/ide/inspire/atom/downloadservice.xml

**Comment by df-git** [comment]
Dear Marisol,
Thank you for your message. We added the certificate also for the INSPIRE Geoportal Linkage checker.
Regarding the INSPIRE Reference Validator you can follow this issue https://github.com/inspire-eu-validation/community/issues/471.

Best regards,
Daniele on behalf of the INSPIRE Support Team

**Comment by df-git** [comment]
Dear Marisol,
I am assuming that this issue has been resolved, since we did not get any feedback.
I therefore close this issue.

Best regards,
Daniele on behalf of the INSPIRE Support Team

**Comment by MarisolGomezAndres** [comment]
Please don´t closet he tiket because it´s not solved.


The Inspire validator and the LinkChecher publshed now  provide the same error about the certificate. (Coupled Resource)

[cid:image001.jpg@01D6FBBD.0CC97B90]

[cid:image002.jpg@01D6FBBD.0CC97B90]

However, in the staging instance the certificate is recogniced and it works. When are you planning to publish in the producction instance?

[cid:image003.jpg@01D6FBBD.0CC97B90]

Regards.

Marisol Gómez Andrés
Paseo Infanta Isabel 1 – 28014 Madrid  - Spain
Information Technology and Communication Department
Web and Gis Services Manager

De: df-git [mailto:notifications@github.com]
Enviado el: viernes, 5 de febrero de 2021 11:23
Para: INSPIRE-MIF/helpdesk-geoportal <helpdesk-geoportal@noreply.github.com>
CC: Gómez Andrés, Soledad <msgomez@mapa.es>; Author <author@noreply.github.com>
Asunto: Re: [INSPIRE-MIF/helpdesk-geoportal] ES: The LinkChecker doesn´t recognize our SDI Digital certificate (#9)


Closed #9<https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/9>.

**Comment by MarisolGomezAndres** [comment]
Thaks.

Un saludo.

María Soledad Gómez Andrés
Jefa de Área de Servicios SIG y Web
SG de Tecnologías de la Información y Comunicaciones
Ministerio de Agricultura, Pesca y Alimentación

De: df-git [mailto:notifications@github.com]
Enviado el: viernes, 5 de febrero de 2021 15:20
Para: INSPIRE-MIF/helpdesk-geoportal <helpdesk-geoportal@noreply.github.com>
CC: Gómez Andrés, Soledad <msgomez@mapa.es>; Author <author@noreply.github.com>
Asunto: Re: [INSPIRE-MIF/helpdesk-geoportal] ES: The LinkChecker doesn´t recognize our SDI Digital certificate (#9)


Reopened #9<https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/9>.

**Comment by dartasensi** [comment]
Dear @MarisolGomezAndres 

I'm not sure the issue you found could be related to the SSL certificates trust chain inside Geoportal.
In fact, I spent some time reviewing all the Root CA certificates that we recently imported, and for your services the only Root CA involved is `AC RAIZ FNMT-RCM`, already included in our truststore since Nov 2019.

Instead, I quickly checked some of Resource Locators and Coupled Resources inside the mentioned URLs.
While the WMS doesn't seem to present any particular issue, the ATOM Download service presents different Link elements that do not always reach any valid metadata document.
For instance, the "self-reference" and "service metadata" elements in the Download Service Feed don't respect the TG requirements and they seems to reference to "Not found" courtesy pages:
````
<link rel="self" type="application/atom+xml" hreflang="es"
        href="https://wmts.mapama.gob.es/ide/inspire/atom/downloadservice.xml" title="Enlace a este mismo documento"/>
<link rel="describedby" hreflang="es" type="application/xml" href="https://wmts.mapama.gob.es/ide/inspire/inspire/metadata/downloadservice_md.xml" title="Enlace a los metadatos del servicio de descarga"/>
````
So, I would suggest to first correct and validate the contents of the ATOM Download service.
Then, if you still encounter some issue with the Linkage Checker, please provide a proper combination of data (dataset metadata, view service metadata, download service metadata) to be check.

Kind regards,
Davide

_Note: for future references, in case you are reading this as email notification, please try to open and reply directly through the GitHub web interface, since the email attachment (ie. images) feature is not well supported yet._

**Comment by MarisolGomezAndres** [comment]
Dear team:

The ticket cannot be closed for the next reason:


·         The Inspire validator and the LinkChecher published now provide the same error about the certificate. (Coupled Resource). It  is solved in the staging instance http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/ but not in the live instance. As you informed us, the certificate will be included in the live instance by the middle of march. After that we will check again and let you know if it works. Then the ticket can be closed.

Regards.

Marisol Gómez Andrés
Information Technology and Communication Department
Web and GIS services Manager

De: Davide Artasensi [mailto:notifications@github.com]
Enviado el: miércoles, 17 de febrero de 2021 7:47
Para: INSPIRE-MIF/helpdesk-geoportal <helpdesk-geoportal@noreply.github.com>
CC: Gómez Andrés, Soledad <msgomez@mapa.es>; Mention <mention@noreply.github.com>
Asunto: Re: [INSPIRE-MIF/helpdesk-geoportal] ES: The LinkChecker doesn´t recognize our SDI Digital certificate (#9)


Closed #9<https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/9>.
